name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party build tools
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm
      - name: build all and examples
        run: |
          # ./build-x86_64.sh
          # ./run-tests.sh
          gcc -o build.exe build.c
          ./build.exe
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party build tools
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm
      - name: build all and examples
        run: |
          ./build-x86_64.sh
          ./run-tests.sh
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build all and examples
        run: |
          ./build.sh
          ./run-tests.sh
        env:
          CC: clang
          CXX: clang++
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build all and examples
        shell: cmd
        # this replaces default PowerShell, which can't fail the build
        run: |
          #./build_msvc.bat examples
          cl.exe build.c
          .\build.exe
# TODO(#21): there is no CI build for FreeBSD
# TODO(#113): the x86_64 examples do not work on Windows
# TODO(#114): the x86_64 examples do not work on MacOS
